flatpak: Change the branch to stable

diff --git a/.github/workflows/flatpak.yml b/.github/workflows/flatpak.yml
--- a/.github/workflows/flatpak.yml
+++ b/.github/workflows/flatpak.yml
@@ -1,174 +1,78 @@
 name: Flatpak
 
-on:
-  release:
-    types: released
+on: push
 
 jobs:
-  part1:
-    name: Part 1/3
+  build:
+    name: org.getmonero.Monero
     if: github.repository == 'monero-project/monero-gui'
-    runs-on: ubuntu-latest
-    container:
-      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
-      options: --privileged
     strategy:
       matrix:
         arch: [x86_64, aarch64]
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        submodules: recursive
-
-    - name: Install deps
-      run: dnf -y install docker
-
-    - name: Setup QEMU
-      uses: docker/setup-qemu-action@v2
-      with:
-        platforms: arm64
-
-    - name: Build flatpak
-      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
-      env:
-        FLATPAK_BUILDER_N_JOBS: 3
-      with:
-        manifest-path: share/org.getmonero.Monero.yaml
-        arch: ${{ matrix.arch }}
-        cache: false
-        stop-at-module: boost
-
-    - name: Tar flatpak-builder
-      run: tar -cvf flatpak-builder.tar .flatpak-builder
-
-    - name: Save flatpak-builder
-      uses: actions/upload-artifact@v3
-      with:
-        name: flatpak-builder-${{ matrix.arch }}
-        path: flatpak-builder.tar
-
-  part2:
-    name: Part 2/3
-    if: github.repository == 'monero-project/monero-gui'
-    needs: part1
-    runs-on: ubuntu-latest
+        include:
+          - arch: x86_64
+            runner: ubuntu-24.04
+          - arch: aarch64
+            runner: ubuntu-24.04-arm
+    runs-on: ${{ matrix.runner }}
     container:
-      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
+      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-5.15-25.08
       options: --privileged
-    strategy:
-      matrix:
-        arch: [x86_64, aarch64]
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v6
+        with:
+          submodules: recursive
 
-    - name: Install deps
-      run: dnf -y install docker
+      - name: Add version and date
+        run: |
+          sed -i 's/@VERSION@/${{ github.event.release.tag_name }}/g' $GITHUB_WORKSPACE/share/org.getmonero.Monero.metainfo.xml
+          sed -i 's/@DATE@/'"$(date '+%F')"'/g' $GITHUB_WORKSPACE/share/org.getmonero.Monero.metainfo.xml
 
-    - name: Setup QEMU
-      uses: docker/setup-qemu-action@v2
-      with:
-        platforms: arm64
+      - name: Validate Flatpak manifest
+        run: flatpak-builder-lint manifest share/org.getmonero.Monero.yaml
 
-    - name: Restore flatpak-builder
-      uses: actions/download-artifact@v4.1.7
-      with:
-        name: flatpak-builder-${{ matrix.arch }}
+      - name: Build flatpak
+        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
+        env:
+          FLATPAK_BUILDER_N_JOBS: 3
+        with:
+          manifest-path: share/org.getmonero.Monero.yaml
+          arch: ${{ matrix.arch }}
+          cache: false
+          branch: stable
+          mirror-screenshots-url: https://dl.flathub.org/media
 
-    - name: Untar flatpak-builder
-      run: tar -xvf flatpak-builder.tar
+      - name: Validate AppStream
+        run: flatpak-builder-lint appstream flatpak_app/files/share/metainfo/org.getmonero.Monero.metainfo.xml
 
-    - name: Build flatpak
-      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
-      env:
-        FLATPAK_BUILDER_N_JOBS: 3
-      with:
-        manifest-path: share/org.getmonero.Monero.yaml
-        arch: ${{ matrix.arch }}
-        cache: false
-        stop-at-module: monero-gui
+      - name: Verify Icon and Metadata in app-info
+        run: |
+          test -f flatpak_app/files/share/app-info/icons/flatpak/128x128/org.getmonero.Monero.png || { echo "::error::Missing 128x128 icon in app-info"; exit 1; }
+          test -f flatpak_app/files/share/app-info/xmls/org.getmonero.Monero.xml.gz || { echo "::error::Missing org.getmonero.Monero.xml.gz in app-info"; exit 1; }
 
-    - name: Tar flatpak-builder
-      run: tar -cvf flatpak-builder.tar .flatpak-builder
+      - name: Validate build directory
+        run: flatpak-builder-lint builddir flatpak_app
 
-    - name: Save flatpak-builder
-      uses: actions/upload-artifact@v3
-      with:
-        name: flatpak-builder-${{ matrix.arch }}
-        path: flatpak-builder.tar
+      - name: Validate repository
+        run: flatpak-builder-lint repo repo
 
-  part3:
-    name: Part 3/3
-    if: github.repository == 'monero-project/monero-gui'
-    needs: [part1, part2]
-    runs-on: ubuntu-latest
-    container:
-      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
-      options: --privileged
-    strategy:
-      matrix:
-        arch: [x86_64, aarch64]
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        submodules: recursive
+      - name: Print hashes
+        working-directory: flatpak_app/files/bin
+        run: |
+          echo "Hashes of the ${{ matrix.arch }} binaries:" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          for bin in monero-blockchain-ancestry monero-blockchain-depth monero-blockchain-export monero-blockchain-import monero-blockchain-mark-spent-outputs monero-blockchain-prune monero-blockchain-prune-known-spent-data monero-blockchain-stats monero-blockchain-usage monerod monero-gen-ssl-cert monero-gen-trusted-multisig monero-wallet-cli monero-wallet-gui monero-wallet-rpc p2pool; do [ -f "$bin" ] && sha256sum "$bin" || echo "$bin not found"; done >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "An example command to check hashes:" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "$ flatpak run --command=sha256sum org.getmonero.Monero /app/bin/monero-wallet-gui" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
-    - name: Add version and date
-      run: |
-        sed -i 's/<version>/${{ github.event.release.tag_name }}/g' $GITHUB_WORKSPACE/share/org.getmonero.Monero.metainfo.xml
-        sed -i 's/<date>/'"$(date '+%F')"'/g' $GITHUB_WORKSPACE/share/org.getmonero.Monero.metainfo.xml
-
-    - name: Install deps
-      run: dnf -y install docker
-
-    - name: Setup QEMU
-      uses: docker/setup-qemu-action@v2
-      with:
-        platforms: arm64
-
-    - name: Restore flatpak-builder
-      uses: actions/download-artifact@v4.1.7
-      with:
-        name: flatpak-builder-${{ matrix.arch }}
-
-    - name: Untar flatpak-builder
-      run: tar -xvf flatpak-builder.tar
-
-    - name: Build flatpak
-      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
-      env:
-        FLATPAK_BUILDER_N_JOBS: 3
-      with:
-        manifest-path: share/org.getmonero.Monero.yaml
-        arch: ${{ matrix.arch }}
-        cache: false
-
-    - name: Validate AppData
-      working-directory: flatpak_app/files/share/appdata
-      run: appstream-util validate org.getmonero.Monero.appdata.xml
-
-    - name: Delete flatpak-builder
-      uses: geekyeggo/delete-artifact@v2
-      with:
-        name: flatpak-builder-${{ matrix.arch }}
-
-    - name: Print hashes
-      working-directory: flatpak_app/files/bin
-      run: |
-        echo "Hashes of the ${{ matrix.arch }} binaries:" >> $GITHUB_STEP_SUMMARY
-        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-        for bin in monero-blockchain-ancestry monero-blockchain-depth monero-blockchain-export monero-blockchain-import monero-blockchain-mark-spent-outputs monero-blockchain-prune monero-blockchain-prune-known-spent-data monero-blockchain-stats monero-blockchain-usage monerod monero-gen-ssl-cert monero-gen-trusted-multisig monero-wallet-cli monero-wallet-gui monero-wallet-rpc p2pool; do sha256sum $bin; done >> $GITHUB_STEP_SUMMARY
-        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-        echo "An example command to check hashes:" >> $GITHUB_STEP_SUMMARY
-        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-        echo "$ flatpak run --command=sha256sum org.getmonero.Monero /app/bin/monero-wallet-gui" >> $GITHUB_STEP_SUMMARY
-        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-
-    - name: Publish to Flathub Beta
-      uses: flatpak/flatpak-github-actions/flat-manager@v6
-      with:
-        flat-manager-url: https://hub.flathub.org
-        repository: beta
-        token: ${{ secrets.FLATHUB_ }}
+      - name: Publish to Flathub
+        uses: flatpak/flatpak-github-actions/flat-manager@v6
+        with:
+          flat-manager-url: https://hub.flathub.org
+          repository: stable
+          build-log-url: https://github.com/monero-project/monero-gui/actions/runs/${{ github.run_id }}
+          token: ${{ secrets.FLATHUB_TOKEN }}
